<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="DESKTOP-I9SD8H5" name="pytest" skipped="0" tests="1" time="0.277" timestamp="2020-05-12T22:01:19.584642"><testcase time="0.000"></testcase><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 188, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\sasneha\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 203, in _multicall
    gen.send(outcome)
  File &quot;C:\Users\sasneha\PycharmProjects\PythonSelfFramework\tests\conftest.py&quot;, line 50, in pytest_runtest_makereport
    _capture_screenshot(file_name)
  File &quot;C:\Users\sasneha\PycharmProjects\PythonSelfFramework\tests\conftest.py&quot;, line 58, in _capture_screenshot
    driver.get_screenshot_as_file(name)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;get_screenshot_as_file&apos;</error></testcase></testsuite></testsuites>